'use strict';
const $=id=>document.getElementById(id);
const modes={sar:{prompt:'There is a little girl in a red jacket who is lost. Find her and keep tracking her.',target:'PERSON LOCATED',object:'PERSON',report:'A girl matching the red-jacket description is located, seated beside the trail. Position pinned. Maintaining visual tracking and an observation orbit for the response team.',search:'Searching the valley. Prioritizing trails and sheltered terrain.',clue:'Possible trail activity detected. Adjusting the sweep to inspect the eastern ridge.'},fire:{prompt:'Check the eastern ridge for signs of fire and monitor any hotspots.',target:'HOTSPOT LOCATED',object:'HOTSPOT',report:'Active brush fire detected on the eastern ridge. Flames and a concentrated thermal hotspot are visible. Position pinned. Orbiting to monitor the fire and surrounding terrain.',search:'Scanning the ridge for thermal anomalies and visible smoke.',clue:'Thermal anomaly detected. Replanning for a closer observation pass.'},security:{prompt:'Secure the perimeter, flag any suspicious activities, and keep inspecting.',target:'VEHICLE TRACKING ENABLED',object:'VEHICLE–01',report:'Unexpected vehicle detected on the restricted access road. Vehicle tracking enabled. Suspending the planned sweep and following the car with RGB and thermal observation.',search:'Surveying the restricted perimeter and access road for unexpected vehicles.',clue:'Moving vehicle detected on the access road.'}};
const HOME={x:210,y:425};
const ORBIT={x:640,y:250,r:62};
let mode='sar',phase='ready',paused=false,elapsed=0,lastFrame=null,orbitAngle=0;
let vehicleDistance=0,vehicleTime=0,vehicleSpeed=0,vehicleTrail=[],vehicleTrailElapsed=0,activeFeed='rgb';
const vehicleRoad=$('vehicle-road'),vehicleRoadLength=vehicleRoad.getTotalLength();
let motion={...HOME,heading:0,scale:1},transition=null,searchStart=0,clueReported=false,telemetryElapsed=0;
const route=$('route'),routeLength=route.getTotalLength();
const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x));
const smooth=x=>x*x*(3-2*x);
function message(content,user=false){const item=document.createElement('div');item.className=user?'user-message':'assistant-message';const label=document.createElement('span');label.className='message-label';label.textContent=user?'YOU / MISSION INTENT':'DEGLA / MISSION CONTROL';const p=document.createElement('p');p.textContent=content;item.append(label,p);$('chat').append(item);$('chat').scrollTop=$('chat').scrollHeight;}
function status(s){$('flight-status').textContent=s;}
function pauseControl(){ $('pause').disabled=phase==='ready';$('pause').textContent=paused?'▶':'Ⅱ';$('pause').setAttribute('aria-label',paused?'Resume simulation':'Pause simulation');$('pov-image').classList.toggle('sensor-paused',paused);}
let suggestionTimer=null,suggestionText='',suggestionTyping=false;
function stopSuggestion(){if(suggestionTimer!==null)clearTimeout(suggestionTimer);suggestionTimer=null;suggestionTyping=false;}
function suggestedCommand(){return phase==='ready'?modes[mode].prompt:$('command').value;}
function fillSuggestedMission(animate=true){stopSuggestion();suggestionText=modes[mode].prompt;$('command').value='';$('command').readOnly=true;$('launch-guide').hidden=false;$('launch').innerHTML='<span>Press <kbd>Enter ↵</kbd> to launch</span>';$('launch').classList.add('enter-prompt');$('send').textContent='↵';$('send').setAttribute('aria-label','Launch selected mission');if(animate)$('command').focus({preventScroll:true});if(!animate||window.matchMedia('(prefers-reduced-motion: reduce)').matches){$('command').value=suggestionText;return;}suggestionTyping=true;let n=0;function type(){n=Math.min(n+2,suggestionText.length);$('command').value=suggestionText.slice(0,n);if(n<suggestionText.length)suggestionTimer=setTimeout(type,16);else{suggestionTimer=null;suggestionTyping=false;}}type();}
function typePrompt(){stopSuggestion();$('launch-guide').hidden=phase!=='ready';$('command').readOnly=phase==='ready';$('launch').classList.remove('enter-prompt');$('send').textContent='↗';$('send').setAttribute('aria-label','Send mission command'); $('command').value='';$('command').placeholder='Type your mission…';$('launch').innerHTML='Type a command… <span>↗</span>'; }
function renderAircraft(){ $('aircraft').setAttribute('transform',`translate(${motion.x.toFixed(3)} ${motion.y.toFixed(3)})`);$('aircraft-body').setAttribute('transform',`rotate(${motion.heading.toFixed(3)}) scale(${motion.scale.toFixed(3)})`); }
function reset(){clearVehicleTracking();phase='ready';elapsed=0;paused=false;orbitAngle=0;transition=null;searchStart=0;clueReported=false;motion={...HOME,heading:0,scale:1};$('experience').classList.remove('running');$('target').setAttribute('visibility','hidden');$('orbit').style.opacity='0';$('pov').hidden=true;renderAircraft();$('altitude').innerHTML='0 <small>m</small>';$('speed').innerHTML='0 <small>m/s</small>';$('battery').innerHTML='98<small>%</small>';$('compute-state').textContent='STANDBY';$('chip').classList.remove('active');[1,2,3].forEach(n=>$('step'+n).classList.remove('active'));route.style.stroke='';$('chat').replaceChildren();message('The aircraft is ready. What’s the mission?');typePrompt();$('launch').innerHTML='Try a search mission <span>↗</span>';status('Ready for your mission');pauseControl();}
function setMode(next){mode=next;reset();document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('selected',b.dataset.mode===mode));$('launch').innerHTML=(mode==='sar'?'Try a search mission':mode==='fire'?'Try a fire mission':'Try vehicle tracking')+' <span>↗</span>';fillSuggestedMission();}
function launch(prompt){clearVehicleTracking();phase='planning';elapsed=0;paused=false;searchStart=0;clueReported=false;$('target').setAttribute('visibility','hidden');$('orbit').style.opacity='0';$('pov').hidden=true;message(prompt,true);message('Intent received. Building a search plan onboard. This demo runs an illustrative mission sequence.');typePrompt();$('experience').classList.add('running');$('chip').classList.add('active');$('step1').classList.add('active');$('compute-state').textContent='PLANNING';status('Understanding intent');pauseControl();}
function pause(){if(phase==='ready')return;paused=!paused;pauseControl();status(paused?'Simulation paused':phase==='vehicle-tracking'?'Vehicle tracking enabled':phase==='tracking'?'Maintaining visual contact':phase==='returning'?'Returning to base':'Mission in progress');}
function pointOnRoute(f){return route.getPointAtLength(clamp(f)*routeLength);}
function routeHeading(f){const a=pointOnRoute(f-.0005),b=pointOnRoute(f+.0005);return Math.atan2(b.y-a.y,b.x-a.x)*180/Math.PI+90;}
function startTransition(end,endHeading,duration){const a={x:motion.x,y:motion.y};const length=Math.hypot(end.x-a.x,end.y-a.y);const reach=Math.min(90,length*.4);const from=(motion.heading-90)*Math.PI/180,to=(endHeading-90)*Math.PI/180;transition={a,b:{x:a.x+Math.cos(from)*reach,y:a.y+Math.sin(from)*reach},c:{x:end.x-Math.cos(to)*reach,y:end.y-Math.sin(to)*reach},d:end,duration};elapsed=0;}
function cubic(t){const {a,b,c,d}=transition,u=1-t;return {x:u*u*u*a.x+3*u*u*t*b.x+3*u*t*t*c.x+t*t*t*d.x,y:u*u*u*a.y+3*u*u*t*b.y+3*u*t*t*c.y+t*t*t*d.y};}
function move(point,heading,dt){motion.x=point.x;motion.y=point.y;const difference=((heading-motion.heading+540)%360+360)%360-180;motion.heading+=difference*(1-Math.exp(-dt*10));}
function transitionFrame(dt){const t=clamp(elapsed/transition.duration),p=cubic(t),next=cubic(Math.min(1,t+.001)),previous=cubic(Math.max(0,t-.001));move(p,Math.atan2(next.y-previous.y,next.x-previous.x)*180/Math.PI+90,dt);return t>=1;}
function command(text){if(!text.trim())return;const q=text.toLowerCase();if(phase==='ready'){if(/fire|smoke|hotspot/.test(q))mode='fire';else if(/perimeter|surveil|security|vehicle|car/.test(q))mode='security';document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('selected',b.dataset.mode===mode));launch(text);return;}message(text,true);$('command').value='';if(/return|land|abort/.test(q)){clearVehicleTracking();phase='returning';paused=false;startTransition(HOME,180,Math.max(5,Math.hypot(motion.x-HOME.x,motion.y-HOME.y)/85));$('orbit').style.opacity='0';$('pov').hidden=true;status('Returning to base');message('Mission updated. Returning to the launch point.');pauseControl();}else if(/resume|continue/.test(q)){if(paused)pause();message('Resuming the mission from the current position.');}else if(/pause|hold|stop/.test(q)){if(!paused)pause();message('Simulation paused. Say “resume” to continue.');}else if(/north|south|east|west|replan|search|sweep/.test(q)){clearVehicleTracking();searchStart=/north/.test(q)?.22:/south/.test(q)?.38:/east/.test(q)?.55:.1;phase='replanning';paused=false;clueReported=false;const end=pointOnRoute(searchStart);startTransition(end,routeHeading(searchStart),Math.max(3,Math.hypot(end.x-motion.x,end.y-motion.y)/85));$('target').setAttribute('visibility','hidden');$('orbit').style.opacity='0';$('pov').hidden=true;route.style.stroke='#e2fbcf';message('Search priority updated in this simulation. Revising the sweep and continuing the mission.');$('compute-state').textContent='REPLANNING';status('Replanning search');pauseControl();}else if(/track|follow|visual/.test(q)&&phase==='vehicle-tracking'){message('Vehicle tracking remains enabled. Following VEHICLE–01; the planned sweep stays suspended. RGB and thermal are locked to the same moving target.');}else if(/orbit|track|visual/.test(q)&&(phase==='tracking'||phase==='approaching')){message('Maintaining the observation orbit. The location and sensor view remain pinned.');}else{message('This demo supports a search mission, search-area replanning, pause, resume, and return to base. Try “search the north ridge” or “return to base”.');}}
function acquired(){$('experience').classList.add('objective-acquired');$('map-route-label').textContent=mode==='sar'?'SUBJECT LOCATED / OBSERVATION ORBIT':'FIRE LOCATED / MONITORING ORBIT';phase='approaching';orbitAngle=0;startTransition({x:ORBIT.x+ORBIT.r,y:ORBIT.y},180,3.5);$('target').setAttribute('visibility','visible');$('target-label').textContent=modes[mode].target;$('pov-title').textContent=modes[mode].target;$('pov-object').textContent=modes[mode].object;$('pov').hidden=false;$('orbit').style.opacity='1';$('compute-state').textContent='TRACKING';status('Acquiring observation orbit');message(modes[mode].report);setFeed(mode==='fire'?'thermal':'rgb');}
function clearVehicleTracking(){$('experience').classList.remove('objective-acquired');$('rescue-camera').hidden=true;$('rescue-camera-hud').hidden=true;$('pov-image').classList.remove('rescue-orbit');$('pov').classList.remove('rescue-pov');vehicleDistance=0;vehicleTime=0;vehicleSpeed=0;vehicleTrail=[];vehicleTrailElapsed=0;$('vehicle-map').setAttribute('visibility','hidden');$('vehicle-trail').setAttribute('d','');$('pursuit-link').setAttribute('d','');$('experience').classList.remove('vehicle-pursuit');$('pov-image').classList.remove('vehicle-feed');$('vehicle-camera').hidden=true;$('vehicle-camera-hud').hidden=true;$('map-route-label').textContent='SEARCH AREA / 0.8 KM²';$('sensor-caption').textContent='SIMULATED SENSOR VIEW';$('track-status').textContent='TRACKING';$('coordinates').textContent='37.1783° N · 10.2471° E';}
function vehiclePoint(distance){return vehicleRoad.getPointAtLength(((distance%vehicleRoadLength)+vehicleRoadLength)%vehicleRoadLength);}
function beginVehicleTracking(){phase='vehicle-tracking';elapsed=0;vehicleTime=0;vehicleDistance=0;vehicleTrail=[];$('experience').classList.add('vehicle-pursuit');$('vehicle-map').setAttribute('visibility','visible');$('target').setAttribute('visibility','hidden');$('orbit').style.opacity='0';$('map-route-label').textContent='SWEEP SUSPENDED / VEHICLE TRACKING';$('pov').hidden=false;$('pov-title').textContent='VEHICLE TRACKING ENABLED';$('pov-object').textContent='VEHICLE–01';$('sensor-caption').textContent='SIMULATED LIVE VIEW';$('track-status').textContent='AUTO TRACK';$('compute-state').textContent='FOLLOWING';status('Vehicle tracking enabled');message(modes.security.report);setFeed('rgb');updateVehicleTracking(0);}
function updateVehicleTracking(dt){vehicleTime+=dt;vehicleSpeed=12+2*Math.sin(vehicleTime*.24);vehicleDistance+=vehicleSpeed*dt;const p=vehiclePoint(vehicleDistance),ahead=vehiclePoint(vehicleDistance+1),behind=vehiclePoint(vehicleDistance-48);const heading=Math.atan2(ahead.y-p.y,ahead.x-p.x)*180/Math.PI+90;$('vehicle-marker').setAttribute('transform',`translate(${p.x.toFixed(2)} ${p.y.toFixed(2)})`);$('vehicle-icon').setAttribute('transform',`rotate(${heading.toFixed(2)})`);const dx=behind.x-motion.x,dy=behind.y-motion.y,dist=Math.hypot(dx,dy);const step=Math.min(dist,Math.max(vehicleSpeed,dist*1.1)*dt,75*dt);if(dist>.001)move({x:motion.x+dx/dist*step,y:motion.y+dy/dist*step},Math.atan2(dy,dx)*180/Math.PI+90,dt);$('pursuit-link').setAttribute('d',`M${motion.x.toFixed(2)} ${motion.y.toFixed(2)} L${p.x.toFixed(2)} ${p.y.toFixed(2)}`);vehicleTrailElapsed+=dt;if(vehicleTrailElapsed>=.2||!vehicleTrail.length){vehicleTrailElapsed=0;vehicleTrail.push([motion.x,motion.y]);if(vehicleTrail.length>220)vehicleTrail.shift();$('vehicle-trail').setAttribute('d',vehicleTrail.map((v,i)=>(i?'L':'M')+v[0].toFixed(1)+' '+v[1].toFixed(1)).join(' '));}$('coordinates').textContent=`${(37.1783+(250-p.y)*.000008).toFixed(5)}° N · ${(10.2471+(p.x-640)*.00001).toFixed(5)}° E`;$('vehicle-speed').textContent=Math.round(vehicleSpeed*.8*3.6)+' KM/H';window.VehicleCamera.draw(vehicleTime,activeFeed,vehicleSpeed);}
function tick(dt){if(paused||phase==='ready')return;elapsed+=dt;telemetryElapsed+=dt;
if(phase==='planning'&&elapsed>=3){phase='takeoff';elapsed=0;$('step2').classList.add('active');message('Search area defined. Sweep planned. Beginning vertical takeoff.');status('Vertical takeoff');}
else if(phase==='takeoff'){motion.scale=1+smooth(clamp(elapsed/5))*.15;if(elapsed>=5){phase='searching';elapsed=0;$('step3').classList.add('active');$('compute-state').textContent='PERCEIVING';status('Autonomous sweep');message(modes[mode].search);}}
else if(phase==='searching'){const fraction=searchStart+(1-searchStart)*clamp(elapsed/(24*(1-searchStart)));move(pointOnRoute(fraction),routeHeading(fraction),dt);if(mode==='security'&&fraction>=.48){beginVehicleTracking();}else{if(!clueReported&&fraction>=.34){clueReported=true;message(modes[mode].clue);$('compute-state').textContent='ADAPTING';status('Inspecting observation');}if(fraction>=(mode==='sar'?.53:.59))acquired();}}
else if(phase==='replanning'){if(transitionFrame(dt)){phase='searching';elapsed=0;$('compute-state').textContent='PERCEIVING';status('Autonomous sweep');}}
else if(phase==='approaching'){if(transitionFrame(dt)){phase='tracking';elapsed=0;status('Maintaining visual contact');}}
else if(phase==='tracking'){orbitAngle+=dt*.22;move({x:ORBIT.x+ORBIT.r*Math.cos(orbitAngle),y:ORBIT.y+ORBIT.r*Math.sin(orbitAngle)},orbitAngle*180/Math.PI+180,dt);}
else if(phase==='vehicle-tracking'){updateVehicleTracking(dt);}
else if(phase==='returning'){const complete=transitionFrame(dt);motion.scale=1+.15*(1-smooth(clamp(elapsed/transition.duration)));if(complete){phase='ready';motion={...HOME,heading:motion.heading,scale:1};status('Landed · Mission complete');$('experience').classList.remove('running');$('compute-state').textContent='STANDBY';$('chip').classList.remove('active');message('Back at the launch point. Mission complete. Ready for the next intent.');typePrompt();fillSuggestedMission(false);pauseControl();}}
if(telemetryElapsed>=.1||phase==='ready'){telemetryElapsed=0;const cruiseAltitude=mode==='sar'?100:65;const alt=phase==='ready'||phase==='planning'?0:phase==='takeoff'?Math.round(cruiseAltitude*smooth(clamp(elapsed/5))):phase==='returning'?Math.round(cruiseAltitude*(1-smooth(clamp(elapsed/transition.duration)))):cruiseAltitude;$('altitude').innerHTML=`${alt} <small>m</small>`;$('speed').innerHTML=`${['ready','planning','takeoff'].includes(phase)?0:phase==='vehicle-tracking'?Math.round(vehicleSpeed*.8):phase==='tracking'?14:18} <small>m/s</small>`;$('battery').innerHTML=`${phase==='ready'?95:phase==='planning'?98:(phase==='tracking'||phase==='vehicle-tracking')?95:97}<small>%</small>`;}
if(mode==='sar'&&(phase==='approaching'||phase==='tracking'))renderRescueCamera();renderAircraft();}
function animate(t){const dt=lastFrame===null?0:Math.min((t-lastFrame)/1000,.05);lastFrame=t;tick(dt);requestAnimationFrame(animate);}
function renderRescueCamera(){const zoom=window.RescueCamera.draw(orbitAngle,activeFeed);$('rescue-camera-status').textContent=String(Math.round((orbitAngle*180/Math.PI)%360)).padStart(3,'0')+'° · 100 m · '+zoom.toFixed(2)+'×';$('track-status').textContent='ORBITING';}
function setFeed(feed){activeFeed=feed;const vehicle=phase==='vehicle-tracking',sar=mode==='sar',fire=mode==='fire';const rescue=sar&&(phase==='approaching'||phase==='tracking');$('rescue-camera').hidden=!rescue;$('rescue-camera-hud').hidden=!rescue;$('pov-image').classList.toggle('rescue-orbit',rescue);$('pov').classList.toggle('rescue-pov',rescue);if(rescue)renderRescueCamera();$('pov-image').classList.toggle('vehicle-feed',vehicle);$('pov-image').classList.toggle('sar-feed',sar);$('pov-image').classList.toggle('fire-feed',fire);$('pov-image').classList.toggle('thermal',feed==='thermal');$('vehicle-camera').hidden=!vehicle;$('vehicle-camera-hud').hidden=!vehicle;if(vehicle){window.VehicleCamera.draw(vehicleTime,activeFeed,vehicleSpeed);$('pov-image').setAttribute('aria-label',feed==='thermal'?'Simulated thermal drone camera following a moving car':'Simulated RGB drone camera following a moving car');}else{$('pov-image').setAttribute('aria-label',fire?(feed==='thermal'?'Generated thermal aerial view showing the heat of a brush fire':'Generated RGB aerial view of flames and smoke on a scrub-covered hillside'):(feed==='thermal'?'Generated thermal aerial view of a girl seated beside a trail':'Generated aerial view of a girl in a red jacket sitting beside a trail'));}$('sensor-rgb').hidden=!sar||feed!=='rgb';$('sensor-thermal').hidden=!sar||feed!=='thermal';$('fire-rgb').hidden=!fire||feed!=='rgb';$('fire-thermal').hidden=!fire||feed!=='thermal';document.querySelectorAll('[data-feed]').forEach(b=>{b.classList.toggle('active',b.dataset.feed===feed);b.setAttribute('aria-pressed',String(b.dataset.feed===feed));});}
document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));document.querySelectorAll('[data-feed]').forEach(b=>b.addEventListener('click',()=>setFeed(b.dataset.feed)));$('command-form').addEventListener('submit',e=>{e.preventDefault();command(suggestedCommand());});$('command').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();command(suggestedCommand());}});$('launch').addEventListener('click',()=>{if(phase==='ready')command(suggestedCommand().trim()||modes[mode].prompt);else $('command').focus();});$('command').addEventListener('beforeinput',stopSuggestion);$('command').addEventListener('input',stopSuggestion);$('reset').addEventListener('click',()=>{reset();fillSuggestedMission();});$('pause').addEventListener('click',pause);document.addEventListener('visibilitychange',()=>{lastFrame=null;});requestAnimationFrame(animate);
$('pilot-form').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.target);const body=`Pilot request for Degla\n\nName: ${data.get('name')}\nEmail: ${data.get('email')}\nOrganization & role: ${data.get('organization')}\nLocation: ${data.get('location')}\n\nMission:\n${data.get('mission')}`;window.location.href=`mailto:ceo@degla.ai?subject=${encodeURIComponent('Degla pilot request — '+data.get('organization'))}&body=${encodeURIComponent(body)}`;$('form-note').textContent='Your email app will open with the request. Send it there to complete your submission. If it does not open, email ceo@degla.ai directly.';});

// Keep the reused swarm scene quiet offscreen and independently pausable.
const swarmFrame=document.getElementById('swarm-map');
const swarmPause=document.getElementById('swarm-pause');
let swarmPaused=window.matchMedia('(prefers-reduced-motion: reduce)').matches,swarmVisible=false;
function syncSwarm(){swarmFrame.contentWindow?.postMessage({type:'degla-swarm',paused:swarmPaused,active:swarmVisible},location.origin);swarmPause.setAttribute('aria-pressed',String(swarmPaused));swarmPause.setAttribute('aria-label',swarmPaused?'Resume swarm animation':'Pause swarm animation');swarmPause.innerHTML=swarmPaused?'▶ <span>Resume</span>':'Ⅱ <span>Pause</span>';}
swarmFrame.addEventListener('load',syncSwarm);
swarmPause.addEventListener('click',()=>{swarmPaused=!swarmPaused;syncSwarm();});
new IntersectionObserver(entries=>{swarmVisible=entries[0].isIntersecting;syncSwarm();},{rootMargin:'100px'}).observe(swarmFrame);

// The default mode is ready to send, and mode buttons animate their editable suggestion.
fillSuggestedMission(false);

// Enter also launches from the page background when the mission surface is visible.
document.addEventListener('keydown',event=>{if(event.defaultPrevented||event.repeat||event.key!=='Enter'||event.shiftKey||event.ctrlKey||event.metaKey||event.altKey||phase!=='ready')return;if(event.target!==document.body)return;const rect=$('experience').getBoundingClientRect();if(rect.top<window.innerHeight&&rect.bottom>150){event.preventDefault();command(suggestedCommand());}});

const dockFrame=document.getElementById("dock-animation");let dockVisible=false;function syncDock(){dockFrame.contentWindow?.postMessage({type:"degla-dock",active:dockVisible},location.origin);}dockFrame.addEventListener("load",syncDock);new IntersectionObserver(entries=>{dockVisible=entries[0].isIntersecting;syncDock();},{rootMargin:"100px"}).observe(dockFrame);

$("launch-guide").addEventListener("click",()=>{if(phase==="ready")command(suggestedCommand());});
